// Counter_Is_Life/vue-counter/src/components/CounterMain.vue
<template>
    <div>
        <h1>Counter</h1>
        <h2>{{ value }}</h2>
        <button @click="setValue(-1)">-</button>
        <button @click="setValue(1)">+</button>
    </div>
</template>

<script lang='ts'>
import Vue from 'vue';
export default Vue.extend({
    props: {
        startedValue: {
            type: Number
        }
    },
    data() {
        return {
            value: this.startedValue || 0
        }
    },
    methods: {
        setValue(delta: number) {
            this.value += delta
        }
    }
})
</script>

<style>

</style>

// Counter_Is_Life/react-counter/src/components/CounterMain.tsx
import React, { Component } from "react";
import CounterValue from "./CounterValue";

interface CounterProps {
    startedValue?: number 
}

interface CounterState {
    value: number
}

export default class CounterMain extends Component<CounterProps, CounterState> {
    public state = { value: this.props.startedValue || 0 }

    private setValue = (delta: number) => {
        this.setState({
            value: this.state.value + delta
        })
    }
    
    render() {
        return (
            <div>
                <CounterValue counter={this.state.value} />
                <button onClick={() => this.setValue(1)}>+</button>
                <button onClick={() => this.setValue(-1)}>-</button>
            </div>
        )
    }
}
